global:
  resolve_timeout: 5m

route:
  receiver: 'slack-alerts'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'slack-alerts'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#monitoring'
    username: 'PrometheusAlertBot'
    icon_emoji: ':warning:'
    send_resolved: true
    title: "{{ range .Alerts }}{{ .Annotations.summary }} {{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
