apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudserver-web-monitor
  labels:
    release: prometheus-stack  # 이 부분 추가
    app: cloudserver-web
spec:
  selector:
    matchLabels:
      app: cloudserver-web
  endpoints:
  - port: http # 서비스에서 매칭되는 포트를 지정합니다
    path: /metrics # 메트릭 경로
    targetPort: 8000 # 메트릭을 수집할 내부 포트를 8000으로 설정합니다
    interval: 30s
  namespaceSelector:
    matchNames:
    - default
