apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloudapp-alerts
  namespace: monitoring  # Prometheus와 동일한 네임스페이스
spec:
  groups:
  - name: cloudapp-rules
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores) by (pod) * 100 > 50
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected on Pod {{ $labels.pod }}"
        description: "Pod {{ $labels.pod }} is using more than 50% CPU for the last 1 minute."
    - alert: PodDown
      expr: kube_pod_container_status_running == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} is down"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is down for more than 1 minute."
    - alert: PodCreated
      expr: changes(kube_pod_created[5m]) > 0
      for: 1m
      labels:
        severity: info
      annotations:
        summary: "New Pod {{ $labels.pod }} created in namespace {{ $labels.namespace }}"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} was created."
