apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloudapp-alerts
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: cloudapp-rules
    rules:
    - alert: HighCPUUsage
      expr: |
        sum by (pod) (
          label_replace(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"cloudserver-web.*"}[5m]), "pod", "$1", "pod", "cloudserver-web-(.*)")
        ) * 100 > 0.1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected on Pod {{ $labels.pod }}"
        description: "Pod {{ $labels.pod }} is using more than 50% CPU for the last 1 minute."
    - alert: PodDown
      expr: kube_pod_container_status_running == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} is down"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is down for more than 1 minute."
    - alert: PodCreated
      expr: changes(kube_deployment_status_replicas{namespace="default", deployment="cloudserver-web"}[5m]) > 0
      for: 1m
      labels:
        severity: info
      annotations:
        summary: "New Pod {{ $labels.pod }} created in namespace {{ $labels.namespace }}"
        description: "New Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} was created."
