apiVersion: v1
kind: Service
metadata:
  name: cloudserver-service
  labels:
    release: prometheus-stack  # Helm 차트의 release 라벨
    app: cloudserver-web
spec:
  selector:
    app: cloudserver-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000  # 기존 서비스의 컨테이너 내부 포트
    nodePort: 30088  # 기존 외부 접근을 위한 포트
    name: http  # 포트 이름 추가
  - protocol: TCP
    port: 8080  # 메트릭 수집을 위한 포트
    targetPort: 8080
    nodePort: 30092   # 외부에서 접속 가능한 메트릭스 포트
    name: metrics  # 메트릭 수집을 위한 포트에 이름 추가
  type: NodePort  # 외부에서 접근 가능하게 설정
