apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudserver-web
  argocd-image-updater.argoproj.io/image-list: khm0930/cloud_storage_web  # Docker Hub의 이미지
  argocd-image-updater.argoproj.io/write-back-method: git  # Git에 이미지 태그를 자동 업데이트
spec:
  replicas: 3  # 원하는 복제본 수
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # 업데이트 중에 동시에 중단 가능한 파드 수
      maxSurge: 1        # 동시에 추가로 생성 가능한 파드 수
  selector:
    matchLabels:
      app: cloudserver-web
  template:
    metadata:
      labels:
        app: cloudserver-web
    spec:
      containers:
      - name: cloudserver-container
        image: khm0930/cloud_storage_web:latest  # Docker Hub에 올린 이미지
        resources:
          requests:
            cpu: "500m"       # 파드가 최소한으로 요구하는 CPU
            memory: "512Mi"   # 파드가 최소한으로 요구하는 메모리
          limits:
            cpu: "1"       # 파드가 사용할 수 있는 최대 CPU
            memory: "1Gi"   # 파드가 사용할 수 있는 최대 메모리
        ports:
        - containerPort: 8000  # 웹 애플리케이션의 포트
        - containerPort: 8080  # 메트릭스를 수집할 포트 (예시로 추가)
        volumeMounts:
        - mountPath: "/media/uploads"  # 파드 내부에서 마운트할 경로
          name: media-storage
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-pvc  # PVC와 연결
