apiVersion: v1
kind: Service
metadata:
  name: cloudserver-service
spec:
  selector:
    app: cloudserver-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000  # 컨테이너 내부 포트
    nodePort: 30088  # 원하는 포트 번호를 지정
  type: NodePort  # 외부에서 접근 가능하게 설정
