apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-load
  template:
    metadata:
      labels:
        app: cpu-load
    spec:
      containers:
      - name: cpu-load-container
        image: busybox
        args:
        - /bin/sh
        - -c
        - "while true; do echo 'Load'; done;"
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"
