apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudserver-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudserver-web
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # memory 사용률이 70% 이상이면 스케일링
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30  #  사용률이 30% 이상이면 스케일링
