apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-load
  template:
    metadata:
      labels:
        app: memory-load
    spec:
      containers:
      - name: memory-load-container
        image: busybox
        args:
        - /bin/sh
        - -c
        - "x=1; while true; do x=\$((x * 2)); done;"
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
