apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport   # 새로운 Prometheus 서비스
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090  # NodePort로 외부에 노출되는 포트
  selector:
    app.kubernetes.io/name: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport   # 새로운 Grafana 서비스
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30030  # NodePort로 외부에 노출되는 포트
  selector:
    app.kubernetes.io/name: grafana

