apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 100Gi  # 원하는 크기로 설정
  accessModes:
    - ReadWriteMany  # 여러 파드에서 동시에 읽고 쓰기 가능
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/cloudstorage/media/uploads  # NFS 서버에서 공유하는 디렉토리 경로
    server: 192.168.1.15  # NFS 서버의 IP 주소
  mountOptions:
    - rw
    - noac  # 필요한 경우 마운트 옵션 추가
