apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteMany # 여러 파드에서 동시에 읽고 쓸 수 있게 설정
  resources:
    requests:
      storage: 100Gi # PV와 일치하는 크기로 설정
