USER-SUPPLIED VALUES:

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
      receiver: 'slack'
    receivers:
      - name: 'slack'
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/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'
            channel: '#server-monitoring'
            send_resolved: true
            text: 'waring'
